---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-nginx-index
data:
  index.html: |
    <html>
      <body>
        <h1>Ini tampilan dari NGINX dan nama saya Rizky Oktamara</h1>
      </body>
    </html>